version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    image: ghcr.io/0xbbeer/sample-app:latest
    ports:
      - "3003:3003"
    command: >
      sh -c "python /app/manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - FROST_API_ID=${FROST_API_ID}
      - FROST_API_PASSWORD=${FROST_API_PASSWORD}
    depends_on:
      - db
    
