# Generated by Django 3.2.9 on 2021-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(blank=True, default='', max_length=512)),
                ('country', models.CharField(blank=True, default='', max_length=512)),
                ('geometry', models.CharField(blank=True, default='', max_length=512)),
                ('municipality', models.CharField(blank=True, default='', max_length=512)),
                ('stationHolder', models.CharField(blank=True, default='', max_length=512)),
                ('validFrom', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
