# Generated by Django 3.2.9 on 2021-12-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frost_met_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='validFrom',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
