# Generated by Django 3.2.9 on 2021-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frost_met_app', '0002_alter_stations_validfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='validFrom',
            new_name='validfrom',
        ),
    ]
