# Generated by Django 3.2.9 on 2021-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frost_met_app', '0003_rename_validfrom_stations_validfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='stationHolder',
            field=models.CharField(blank=True, default='-', max_length=512),
        ),
    ]
