# Generated by Django 3.2.9 on 2021-12-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frost_met_app', '0004_alter_stations_stationholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='stationHolder',
            new_name='stationholder',
        ),
    ]
